In [1]:
import numpy as np

vector1 = np.array([1, 2, 3, 4, 5])

print(vector1)

[1 2 3 4 5]


In [2]:
for i in vector1:
    print(i)

1
2
3
4
5


In [5]:
print(vector1[1:])
print(vector1[1:3])
print(vector1[1:4:2])

[2 3 4 5]
[2 3]
[2 4]


In [12]:

vector1 = np.zeros((2, 3))


vector1


array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# Linspace skapar en vektor från en del av space
x = np.linspace(-5, 5) # default, 50 equally numbers between low and high

x

array([-5.        , -4.79591837, -4.59183673, -4.3877551 , -4.18367347,
       -3.97959184, -3.7755102 , -3.57142857, -3.36734694, -3.16326531,
       -2.95918367, -2.75510204, -2.55102041, -2.34693878, -2.14285714,
       -1.93877551, -1.73469388, -1.53061224, -1.32653061, -1.12244898,
       -0.91836735, -0.71428571, -0.51020408, -0.30612245, -0.10204082,
        0.10204082,  0.30612245,  0.51020408,  0.71428571,  0.91836735,
        1.12244898,  1.32653061,  1.53061224,  1.73469388,  1.93877551,
        2.14285714,  2.34693878,  2.55102041,  2.75510204,  2.95918367,
        3.16326531,  3.36734694,  3.57142857,  3.7755102 ,  3.97959184,
        4.18367347,  4.3877551 ,  4.59183673,  4.79591837,  5.        ])